name: test

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry add black flake8 isort
      - name: linting
        run: |
          poetry run flake8 .
          poetry run black . --check
          poetry run isort .
  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        django-version: ["2.2", "3.0", "3.1", "3.2"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Install django ${{ matrix.django-version }}
        run: poetry add "Django==${{ matrix.django-version }}"

      - name: Run tests
        run: |
          poetry run python makemigrations.py
          poetry run coverage run runtests.py
          poetry run coverage report
          poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
